6daserver:
    port: 8080
app:
    ad-domain: AD.CLUSTER
    ad-server: ldap://DC.AD.CLUSTER
    service-principal: HTTP/intel-nuc10.cluster@AD.CLUSTER
    keytab-location: /Users/mares/tmp/Code-Addict-Repos/active-directory/conf/tomcat.keytab
    ldap-search-base: dc=AD,dc=CLUSTER
    ldap-search-filter: "(| (userPrincipalName={0}) (sAMAccountName={0}))"
spring:
  main:
    allow-bean-definition-overriding: true